apiVersion: v1
kind: ConfigMap
metadata: {name: homework-config, namespace: rudray-devops-hw}
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DEFAULT_CURRENCY: "INR"
---
apiVersion: v1
kind: ConfigMap
metadata: {name: homework-pages, namespace: rudray-devops-hw}
data:
  index.html: |
    <!doctype html>
    <html lang="en"><head><meta charset="utf-8"><title>DevOps Homework</title></head>
    <body><h1>Hello World from Kubernetes</h1><p>Rudray Mehra — 10425</p></body></html>
