#!/usr/bin/env bash
# Core objects: Pod, ReplicaSet, Deployment, DaemonSet, StatefulSet - using the course manifests unmodified.
. "$(dirname "$0")/lib.sh"

hr "POD - smallest deployable unit"
x "kubectl apply -f pod/nginx-pod.yaml"
x "kubectl wait --for=condition=Ready pod/yatri-demo-pod --timeout=120s"
x "kubectl get pod yatri-demo-pod -o wide --show-labels"
x "kubectl describe pod yatri-demo-pod | grep -E '^(Node|IP|Status):|Image:|Limits|Requests|cpu|memory'"
x "kubectl apply -f hello.yml                      # restartPolicy: Never, runs one command and exits"
x "kubectl wait --for=jsonpath='{.status.phase}'=Succeeded pod/hello-pod --timeout=120s"
x "kubectl get pod hello-pod"
x "kubectl logs hello-pod"
x "kubectl apply -f k8s-core-objects/pod.yml       # two containers in one pod"
x "kubectl wait --for=condition=Ready pod/mypod --timeout=120s"
x "kubectl get pod mypod"
x "kubectl logs mypod -c logger --tail=2"
x "kubectl exec mypod -c logger -- wget -qO- http://localhost | grep -o '<title>.*</title>'   # containers in a pod share localhost"
x "kubectl delete pod yatri-demo-pod hello-pod mypod"

hr "REPLICASET - keeps N identical pods alive"
x "kubectl apply -f replicaset/backend-rs.yaml"
x "kubectl wait --for=condition=Ready pod -l app=yatri-backend --timeout=180s"
x "kubectl get rs yatri-backend-rs"
x "kubectl get pods -l app=yatri-backend -o wide"
VICTIM=$(kubectl get pods -l app=yatri-backend -o jsonpath='{.items[0].metadata.name}')
watch_start "$L/01-replicaset-selfheal-watch.txt" -l app=yatri-backend
x "kubectl delete pod $VICTIM                     # kill one pod on purpose"
x "sleep 8; kubectl get pods -l app=yatri-backend    # a replacement appeared within seconds"
watch_stop
x "cat '$L/01-replicaset-selfheal-watch.txt'"
x "kubectl scale rs yatri-backend-rs --replicas=5 && sleep 6 && kubectl get rs yatri-backend-rs"
x "kubectl scale rs yatri-backend-rs --replicas=3 && sleep 6 && kubectl get rs yatri-backend-rs"
x "kubectl patch rs yatri-backend-rs --type=json -p='[{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/image\",\"value\":\"python:3.11-alpine3.19\"}]'"
x "kubectl get rs yatri-backend-rs -o jsonpath='template image: {.spec.template.spec.containers[0].image}{\"\\n\"}'"
x "kubectl get pods -l app=yatri-backend -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[0].image'   # existing pods NOT updated: a ReplicaSet has no rollout logic"
x "kubectl delete rs yatri-backend-rs"
x "sleep 3; kubectl get pods -l app=yatri-backend   # deleting the RS cascades to its pods"
x "kubectl wait --for=delete pod -l app=yatri-backend --timeout=120s   # python as PID 1 ignores SIGTERM, so pods use the full 30s grace period"

hr "DEPLOYMENT - manages ReplicaSets, gives rollouts and rollbacks"
x "kubectl apply -f deployment/deployment-v1.yaml"
x "kubectl rollout status deployment/yatri-backend"
x "kubectl get deploy,rs,pods -l app=yatri-backend"
x "kubectl apply -f deployment/deployment-v2.yaml"
x "kubectl rollout status deployment/yatri-backend"
x "kubectl wait --for=delete pod -l app=yatri-backend,version=1.0.0 --timeout=120s"
x "kubectl get pods -l app=yatri-backend -L version"
x "kubectl get rs -l app=yatri-backend             # old RS kept at 0 replicas for rollback"
x "kubectl rollout history deployment/yatri-backend"
x "kubectl logs deployment/yatri-backend --tail=1"
hr "DEPLOYMENT - a broken rollout stops itself (troubleshooting/broken-image.yaml)"
x "kubectl apply -f troubleshooting/broken-image.yaml"
x "sleep 25; kubectl get pods -l app=yatri-backend"
x "kubectl rollout status deployment/yatri-backend --timeout=10s || true"
x "kubectl get deployment yatri-backend           # 3/3 READY: old pods kept serving because maxUnavailable: 0"
x "kubectl rollout undo deployment/yatri-backend"
x "kubectl rollout status deployment/yatri-backend"
x "kubectl wait --for=delete pod -l app=yatri-backend,version=broken-v3 --timeout=120s"
x "kubectl get pods -l app=yatri-backend -o custom-columns='NAME:.metadata.name,VERSION:.metadata.labels.version,STATUS:.status.phase'"
x "kubectl rollout history deployment/yatri-backend"
hr "DEPLOYMENT - selector must match template labels (troubleshooting/selector-mismatch.yaml)"
x "kubectl apply -f troubleshooting/selector-mismatch.yaml || true"
x "kubectl delete deployment yatri-backend"
x "kubectl wait --for=delete pod -l app=yatri-backend --timeout=120s"

hr "DAEMONSET - one pod per node"
x "kubectl apply -f daemonset/node-agent-ds.yaml"
x "kubectl rollout status daemonset/node-logging-agent"
x "kubectl get daemonset node-logging-agent"
x "kubectl get pods -l app=node-logging-agent -o wide"
x "kubectl describe node kushal-lab-control-plane | grep -A1 '^Taints'   # why the control-plane node got no pod"
x "kubectl logs -l app=node-logging-agent --tail=1 | sed -E 's/^\\[[^]]*\\] //'   # each agent reports its own pod/hostname"
x "kubectl get daemonset -n kube-system            # kube-proxy and kindnet tolerate the taint, so they run on all 3 nodes"
x "kubectl delete -f daemonset/node-agent-ds.yaml"

hr "STATEFULSET - stable names, ordered start, one PVC per pod"
x "kubectl apply -f k8s-core-objects/statefulset.yml"
x "sleep 20; kubectl get statefulset mysql; kubectl get pods -l app=mysql; kubectl get pvc"
x "kubectl describe pod mysql-0 | grep -iE 'Failed|no match|platform' | head -3"
x "kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}: {.status.nodeInfo.architecture}{\"\\n\"}{end}'"
x "kubectl set image statefulset/mysql mysql=mysql:8.0    # mysql:5.7 has no arm64 image; 8.0 is multi-arch. Manifest on disk left unchanged."
x "kubectl delete pod mysql-0                            # let the controller recreate it with the new image"
watch_start "$L/01-statefulset-ordered-watch.txt" -l app=mysql
x "kubectl rollout status statefulset/mysql --timeout=600s"
watch_stop
x "cat '$L/01-statefulset-ordered-watch.txt'"
x "kubectl get pods -l app=mysql -o wide"
x "kubectl get pvc"
x "kubectl create service clusterip mysql --clusterip=None --tcp=3306   # the headless service the manifest's serviceName refers to"
x "runonce dns-test busybox:1.36 nslookup mysql-1.mysql.default.svc.cluster.local | grep -A1 '^Name'"
x "runonce dns-test2 busybox:1.36 nslookup mysql | grep -c 'Address: 10.244'   # headless: one A record per pod, no virtual IP"
x "kubectl delete pod mysql-1 && sleep 25 && kubectl get pods -l app=mysql   # same name comes back, same PVC"
x "kubectl exec mysql-1 -- mysql -uroot -ppassword -e 'SELECT VERSION();' 2>/dev/null || (sleep 20; kubectl exec mysql-1 -- mysql -uroot -ppassword -e 'SELECT VERSION();' 2>/dev/null)"
x "kubectl delete statefulset mysql; kubectl delete service mysql"
x "kubectl get pvc                                       # PVCs deliberately survive the StatefulSet"
x "kubectl delete pvc -l app=mysql"
