{
 "title": "S20 - podinfo (24BCS10267)",
 "tags": [
  "s20",
  "session20"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU (cores) per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"s20\", container=\"podinfo\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory working set (bytes) per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"s20\", container=\"podinfo\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP requests/s (app metric)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{namespace=\"s20\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Targets up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(up{namespace=\"s20\", job=\"podinfo\"})"
    }
   ]
  }
 ]
}