apiVersion: v1
kind: ConfigMap
metadata:
  name: stockpilot-config
  namespace: final-k8s
  labels: {app: stockpilot-api}
data:
  APP_ENV: k8s-plain
  APP_VERSION: "1.0.1"
  LOG_LEVEL: info
  DEFAULT_REORDER_LEVEL: "10"
  DB_HOST: stockpilot-postgres
  DB_PORT: "5432"
  DB_NAME: stockpilot
