apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
  labels: {{- include "notes.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
