apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
  labels:
    app: myapp-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-canary
  template:
    metadata:
      labels:
        app: myapp-canary
        track: canary
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 'CANARY v2' > /usr/share/nginx/html/index.html"]