apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
  labels:
    app: myapp-canary
spec:
  replicas: 9
  selector:
    matchLabels:
      app: myapp-canary
  template:
    metadata:
      labels:
        app: myapp-canary
        track: stable
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 'STABLE v1' > /usr/share/nginx/html/index.html"]