apiVersion: v1
kind: Pod
metadata:
  name: storage-demo
spec:
  containers:
    - name: app
      image: nginx:1.27
      volumeMounts:
        - name: persistent-storage
          mountPath: /data      #previously it was data now i changed it to  antara.
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: student-pvc
