apiVersion: v1
kind: PersistentVolume
metadata:
  name: student-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce   #read about readonlymany and readwritemany and readonlyonce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/student-data
