{{- if not .Values.postgres.existingSecret }}
{{- $name := printf "%s-db" (include "taskboard.name" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "taskboard.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  DB_USER: {{ .Values.postgres.username | b64enc | quote }}
  {{- if and $existing $existing.data }}
  DB_PASSWORD: {{ index $existing.data "DB_PASSWORD" | quote }}
  {{- else }}
  DB_PASSWORD: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
