{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "taskboard.name" . }}-backend
  labels: {{- include "taskboard.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels: {{- include "taskboard.selector" (list . "backend") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
