frontend:
  image: ghcr.io/anshalkumar/taskboard-frontend
  tag: latest
  pullPolicy: IfNotPresent
backend:
  image: ghcr.io/anshalkumar/taskboard-backend
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 2
namespace: taskboard
imagePullSecrets: []
app:
  environment: development
  logLevel: INFO
postgres:
  host: taskboard-postgres
  database: taskboard
  username: taskboard
  password: taskboard
  persistence:
    enabled: true
    size: 5Gi
ingress:
  enabled: false
  host: taskboard.local
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {cpu: 500m, memory: 512Mi}
monitoring:
  serviceMonitor:
    enabled: true
