apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-storage
  labels:
    type: local
    environment: staging
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/local-pv-storage
