apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-bg
      version: blue
  template:
    metadata:
      labels:
        app: web-bg
        version: blue
    spec:
      containers:
        - name: web
          image: hashicorp/http-echo:1.0
          args: ["-text=BLUE (v1)", "-listen=:8080"]
          ports:
            - containerPort: 8080
