apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
spec:
  type: LoadBalancer       # asks the cloud provider for an external LB
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 5678
