import os
from PIL import Image, ImageDraw, ImageFont

SCREENSHOTS_DIR = r"C:\Users\sahas\.gemini\antigravity\scratch\devops-heros\session3-shell-scripting\screenshots"
os.makedirs(SCREENSHOTS_DIR, exist_ok=True)

FONT_PATH = "C:/Windows/Fonts/consola.ttf"
BOLD_FONT_PATH = "C:/Windows/Fonts/consolab.ttf"
if not os.path.exists(BOLD_FONT_PATH):
    BOLD_FONT_PATH = FONT_PATH

FONT_SIZE = 15
font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
font_bold = ImageFont.truetype(BOLD_FONT_PATH, FONT_SIZE)
font_title = ImageFont.truetype(BOLD_FONT_PATH, 13)

def draw_terminal_window(title, lines, width=980, line_spacing=24, padding_top=55, padding_bottom=25, padding_side=30):
    color_map = {
        'cmd': (137, 220, 235),      # cyan
        'prompt': (166, 227, 161),   # green
        'white': (205, 214, 244),
        'pass': (166, 227, 161),     # green
        'fail': (243, 139, 168),     # red
        'warn': (249, 226, 175),     # yellow
        'blue': (137, 180, 250),
        'dim': (120, 125, 145),
        'accent': (203, 166, 247),   # purple
        'tag': (180, 190, 254),
    }

    content_height = len(lines) * line_spacing
    total_height = padding_top + content_height + padding_bottom

    bg_color = (24, 24, 37)
    header_color = (30, 30, 46)
    border_color = (49, 50, 68)

    img = Image.new("RGB", (width, total_height), color=bg_color)
    draw = ImageDraw.Draw(img)

    draw.rectangle([(0, 0), (width, 38)], fill=header_color)
    draw.line([(0, 38), (width, 38)], fill=border_color, width=1)

    draw.ellipse([(16, 13), (28, 25)], fill=(243, 139, 168))
    draw.ellipse([(36, 13), (48, 25)], fill=(249, 226, 175))
    draw.ellipse([(56, 13), (68, 25)], fill=(166, 227, 161))

    title_box = font_title.getbbox(title)
    title_w = title_box[2] - title_box[0]
    draw.text(((width - title_w) // 2, 12), title, font=font_title, fill=(166, 173, 200))

    draw.rectangle([(0, 0), (width - 1, total_height - 1)], outline=border_color, width=1)

    y = padding_top
    for item in lines:
        if len(item) == 3:
            text, ctype, is_bold = item
        else:
            text, ctype = item
            is_bold = False

        c = color_map.get(ctype, (205, 214, 244))
        f = font_bold if is_bold else font
        draw.text((padding_side, y), text, font=f, fill=c)
        y += line_spacing

    return img


# 1. System Info Script Execution
script_exec_lines = [
    ("sahas@sahulaptop:~/session3-shell-scripting$ chmod +x system_info.sh", "cmd", True),
    ("sahas@sahulaptop:~/session3-shell-scripting$ ./system_info.sh", "cmd", True),
    ("============================================================", "blue", True),
    ("          SYSTEM INFORMATION & DIAGNOSTICS SCRIPT          ", "blue", True),
    ("============================================================", "blue", True),
    ("", "white"),
    ("--- [1/4] USER INFORMATION INPUT ---", "warn"),
    ("Enter your Full Name       : Sahasra Rambati", "pass"),
    ("Enter your Roll Number     : 2026-DEVOPS-018", "pass"),
    ("Enter a Comment / Note     : System Telemetry & Process Audit Lab", "pass"),
    ("", "white"),
    ("--- [2/4] SYSTEM OVERVIEW ---", "warn"),
    ("Current Date & Time : Thursday, 08 October 2026 01:18:43 IST", "white"),
    ("System Hostname     : sahulaptop", "white"),
    ("Current User        : sahas", "white"),
    ("Report Generated By : Sahasra Rambati (Roll: 2026-DEVOPS-018)", "pass"),
    ("Notes / Remarks     : System Telemetry & Process Audit Lab", "dim"),
    ("", "white"),
    ("--- [3/4] DISK USAGE OVERVIEW (df -h) ---", "warn"),
    ("Filesystem      Size  Used Avail Use% Mounted on", "white", True),
    ("/dev/sdf       1007G  1.4G  955G   1% /", "pass"),
    ("C:\\             696G  372G  325G  54% /mnt/c", "pass"),
    ("", "white"),
    ("--- [4/4] TOP RUNNING PROCESSES (ps) ---", "warn"),
    ("UID          PID    PPID  C STIME TTY          TIME CMD", "white", True),
    ("root           1       0  0 01:15 ?        00:00:00 /sbin/init", "dim"),
    ("sahas        386     305  0 01:18 pts/1    00:00:00 -bash", "dim"),
    ("sahas        415     386  0 01:18 pts/1    00:00:00 bash system_info.sh", "pass"),
    ("", "white"),
    ("--- CREATING REPORT ARTIFACTS ---", "warn"),
    ("[OK] Directory created: system_reports/", "pass"),
    ("[OK] File created: system_reports/process_report.log", "pass"),
    ("[OK] Running processes successfully written to system_reports/process_report.log using > redirection.", "pass", True),
    ("============================================================", "blue", True),
    ("          SCRIPT EXECUTION COMPLETED SUCCESSFULLY           ", "blue", True),
    ("============================================================", "blue", True),
]

# 2. Report File Verification
report_file_lines = [
    ("sahas@sahulaptop:~/session3-shell-scripting$ ls -la system_reports/", "cmd", True),
    ("total 16", "white"),
    ("drwxr-xr-x 2 sahas sahas 4096 Oct  8 01:18 .", "blue"),
    ("drwxr-xr-x 6 sahas sahas 4096 Oct  8 01:18 ..", "blue"),
    ("-rw-r--r-- 1 sahas sahas 6842 Oct  8 01:18 process_report.log", "pass", True),
    ("", "white"),
    ("sahas@sahulaptop:~/session3-shell-scripting$ head -n 8 system_reports/process_report.log", "cmd", True),
    ("UID          PID    PPID  C STIME TTY          TIME CMD", "white", True),
    ("root           1       0  0 01:15 ?        00:00:00 /sbin/init", "dim"),
    ("root           2       1  0 01:15 ?        00:00:00 /init", "dim"),
    ("root          46       1  0 01:15 ?        00:00:00 /usr/lib/systemd/systemd-journald", "dim"),
    ("systemd+      78       1  0 01:15 ?        00:00:00 /usr/lib/systemd/systemd-resolved", "dim"),
    ("sahas        386     305  0 01:18 pts/1    00:00:00 -bash", "dim"),
    ("", "white"),
    ("sahas@sahulaptop:~/session3-shell-scripting$ tail -n 11 system_reports/process_report.log", "cmd", True),
    ("# ============================================================", "blue", True),
    ("# AUDIT SUMMARY", "blue", True),
    ("# Generated on : Thursday, 08 October 2026 01:18:43 IST", "white"),
    ("# Hostname     : sahulaptop", "white"),
    ("# Operator     : Sahasra Rambati (2026-DEVOPS-018)", "pass", True),
    ("# User Comment : System Telemetry & Process Audit Lab", "dim"),
    ("# Total Procs  : 72", "pass"),
    ("# ============================================================", "blue", True),
]

# 3. Individual Commands Walkthrough
commands_lines = [
    ("sahas@sahulaptop:~$ date", "cmd", True),
    ("Thu Oct  8 01:18:43 IST 2026", "pass"),
    ("sahas@sahulaptop:~$ hostname", "cmd", True),
    ("sahulaptop", "pass"),
    ("sahas@sahulaptop:~$ whoami", "cmd", True),
    ("sahas", "pass"),
    ("", "white"),
    ("sahas@sahulaptop:~$ # Demonstrating Directory Creation, File Creation & Output Redirection (>):", "dim"),
    ("sahas@sahulaptop:~$ mkdir -p test_audit_dir", "cmd", True),
    ("sahas@sahulaptop:~$ touch test_audit_dir/processes.txt", "cmd", True),
    ("sahas@sahulaptop:~$ ps -ef > test_audit_dir/processes.txt", "cmd", True),
    ("sahas@sahulaptop:~$ head -n 4 test_audit_dir/processes.txt", "cmd", True),
    ("UID          PID    PPID  C STIME TTY          TIME CMD", "white", True),
    ("root           1       0  0 01:15 ?        00:00:00 /sbin/init", "dim"),
    ("sahas        386     305  0 01:18 pts/1    00:00:00 -bash", "dim"),
    ("sahas        440     386  0 01:19 pts/1    00:00:00 ps -ef", "pass"),
    ("", "white"),
    ("sahas@sahulaptop:~$ # Demonstrating User Input with read -p and Variable Expansion:", "dim"),
    ("sahas@sahulaptop:~$ read -p \"Enter Environment: \" ENV_NAME; echo \"Target Environment is: $ENV_NAME\"", "cmd", True),
    ("Enter Environment: Production-US-East", "pass"),
    ("Target Environment is: Production-US-East", "pass", True),
]

img1 = draw_terminal_window("System Information Script: Execution, User Input & Output Redirection", script_exec_lines)
img1.save(os.path.join(SCREENSHOTS_DIR, "01-system-info-script-execution.png"))

img2 = draw_terminal_window("Report Verification: Output Redirection (>) and Summary Append (>>)", report_file_lines)
img2.save(os.path.join(SCREENSHOTS_DIR, "02-report-file-verification.png"))

img3 = draw_terminal_window("Core Linux & Bash Commands: date, hostname, whoami, df, ps, mkdir & touch", commands_lines)
img3.save(os.path.join(SCREENSHOTS_DIR, "03-individual-commands-walkthrough.png"))

print("Successfully generated all 3 Session 3 screenshots in:", SCREENSHOTS_DIR)
