#!/bin/bash
# ==============================================================================
# Script Name : system_info.sh
# Purpose     : Automated System Information & Process Telemetry Script
# Author      : DevOps Student
# Session     : Session 3 - Shell Scripting
# ==============================================================================

set -euo pipefail

# --- 1. Variables Definition ---
CURRENT_DATE=$(date "+%A, %d %B %Y %T %Z")
SYSTEM_HOSTNAME=$(hostname)
CURRENT_USER=$(whoami)
OUTPUT_DIR="system_reports"
REPORT_FILE="${OUTPUT_DIR}/process_report.log"

echo "============================================================"
echo "          SYSTEM INFORMATION & DIAGNOSTICS SCRIPT          "
echo "============================================================"
echo ""

# --- 2. User Input via read -p ---
echo "--- [1/4] USER INFORMATION INPUT ---"
read -p "Enter your Full Name       : " STUDENT_NAME
read -p "Enter your Roll Number      : " ROLL_NUMBER
read -p "Enter a Comment / Note     : " USER_COMMENT
echo ""

# --- 3. Display System Telemetry to Terminal ---
echo "--- [2/4] SYSTEM OVERVIEW ---"
echo "Current Date & Time : ${CURRENT_DATE}"
echo "System Hostname     : ${SYSTEM_HOSTNAME}"
echo "Current User        : ${CURRENT_USER}"
echo "Report Generated By : ${STUDENT_NAME} (Roll: ${ROLL_NUMBER})"
echo "Notes / Remarks     : ${USER_COMMENT}"
echo ""

echo "--- [3/4] DISK USAGE OVERVIEW (df -h) ---"
df -h
echo ""

echo "--- [4/4] TOP RUNNING PROCESSES (ps) ---"
ps -ef | head -n 10
echo ""

# --- 4. Directory & File Creation ---
echo "--- CREATING REPORT ARTIFACTS ---"
mkdir -p "${OUTPUT_DIR}"
echo "[OK] Directory created: ${OUTPUT_DIR}/"

touch "${REPORT_FILE}"
echo "[OK] File created: ${REPORT_FILE}"

# --- 5. Storing Process Information using > Redirection ---
# Redirect process list to the file (overwriting with >)
ps -ef > "${REPORT_FILE}"

# Append summary header to report using >>
cat <<EOF >> "${REPORT_FILE}"

# ============================================================
# AUDIT SUMMARY
# Generated on : ${CURRENT_DATE}
# Hostname     : ${SYSTEM_HOSTNAME}
# Operator     : ${STUDENT_NAME} (${ROLL_NUMBER})
# User Comment : ${USER_COMMENT}
# Total Procs  : $(ps -ef | wc -l)
# ============================================================
EOF

echo "[OK] Running processes successfully written to ${REPORT_FILE} using > redirection."
echo ""
echo "============================================================"
echo "          SCRIPT EXECUTION COMPLETED SUCCESSFULLY           "
echo "============================================================"
