{
 "title": "Session 21 - Chhavi TaskBoard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total API requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 9 },
   "targets": [
    {
     "expr": "sum(http_requests_total{namespace=\"taskboard\"})"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"taskboard\"}[2m]))"
    }
   ]
  },
  {
   "title": "API scrape targets UP",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 9 },
   "targets": [
    {
     "expr": "sum(up{namespace=\"taskboard\"})"
    }
   ]
  }
 ]
}