#!/usr/bin/env bash
# Session 19 / step 1: init -> fmt -> validate -> plan -> apply the whole VPC + EC2 + S3 stack against LocalStack.
cd "$(dirname "$0")/.." && . scripts/lib.sh
cd terraform-project
V="-var-file=localstack.tfvars"
hr "PROJECT FILES"
x "ls -A . scripts"
x "cat versions.tf provider.tf"
x "cat variables.tf"
x "cat main.tf"
x "cat outputs.tf"
x "cat terraform.tfvars localstack.tfvars"
x "cat scripts/user_data.sh"
hr "LOCALSTACK IS EMPTY BEFORE WE START"
x "awsl ec2 describe-vpcs --query 'Vpcs[].{VpcId:VpcId,Cidr:CidrBlock,Default:IsDefault}' --output table"
x "awsl ec2 describe-instances --query 'Reservations[].Instances[].InstanceId' --output text; echo '(no instances)'"
x "awsl s3 ls; echo '(no buckets)'"
hr "terraform init"
x "rm -rf .terraform terraform.tfstate terraform.tfstate.backup tfplan"
x "tf init -input=false"
x "cat .terraform.lock.hcl | grep -E 'provider|version'"
hr "terraform fmt + validate"
x "tf fmt -recursive -check -diff; echo \"fmt exit code: \$?\""
x "tf validate"
hr "terraform plan"
x "tf plan -input=false $V -out=tfplan"
x "tf show tfplan | grep -E '^  # |Plan:'"
hr "terraform apply"
x "tf apply -input=false -auto-approve tfplan"
hr "outputs"
x "tf output"
x "rm -f tfplan"
