#!/usr/bin/env bash
# Session 19 / step 2: prove the resources exist with the AWS CLI, then look at Terraform state and the dependency graph.
cd "$(dirname "$0")/.." && . scripts/lib.sh
cd terraform-project
V="-var-file=localstack.tfvars"
hr "AWS CLI: the VPC and everything in it"
x "awsl ec2 describe-vpcs --filters Name=tag:Name,Values=s19-kushal-vpc --query 'Vpcs[].{VpcId:VpcId,Cidr:CidrBlock,State:State,DnsHostnames:EnableDnsHostnames}' --output table"
x "awsl ec2 describe-subnets --filters Name=tag:Name,Values=s19-kushal-public-subnet --query 'Subnets[].{SubnetId:SubnetId,Cidr:CidrBlock,AZ:AvailabilityZone,PublicIpOnLaunch:MapPublicIpOnLaunch,Free:AvailableIpAddressCount}' --output table"
x "awsl ec2 describe-internet-gateways --filters Name=tag:Name,Values=s19-kushal-igw --query 'InternetGateways[].{IgwId:InternetGatewayId,AttachedTo:Attachments[0].VpcId,State:Attachments[0].State}' --output table"
x "awsl ec2 describe-route-tables --filters Name=tag:Name,Values=s19-kushal-public-rt --query 'RouteTables[0].Routes[].{Dest:DestinationCidrBlock,Target:GatewayId,State:State}' --output table"
x "awsl ec2 describe-route-tables --filters Name=tag:Name,Values=s19-kushal-public-rt --query 'RouteTables[0].Associations[].{SubnetId:SubnetId,Main:Main}' --output table"
x "awsl ec2 describe-security-groups --filters Name=group-name,Values=s19-kushal-web-sg --query 'SecurityGroups[0].IpPermissions[].{From:FromPort,To:ToPort,Proto:IpProtocol,Cidr:IpRanges[0].CidrIp,Desc:IpRanges[0].Description}' --output table"
x "awsl ec2 describe-instances --filters Name=tag:Name,Values=s19-kushal-web --query 'Reservations[].Instances[].{Id:InstanceId,State:State.Name,Type:InstanceType,AMI:ImageId,Subnet:SubnetId,PrivateIp:PrivateIpAddress,PublicIp:PublicIpAddress,Key:KeyName,SG:SecurityGroups[0].GroupName}' --output table"
x "awsl ec2 describe-instance-attribute --instance-id \$(tf output -raw instance_id) --attribute userData --query 'UserData.Value' --output text | base64 --decode | head -5"
x "awsl ec2 describe-key-pairs --key-names s19-kushal-key --query 'KeyPairs[].{Name:KeyName,Type:KeyType}' --output table"
hr "AWS CLI: the bucket"
x "awsl s3 ls"
x "awsl s3api get-public-access-block --bucket \$(tf output -raw bucket_name) --query PublicAccessBlockConfiguration"
x "awsl s3 ls s3://\$(tf output -raw bucket_name) --recursive"
x "awsl s3 cp s3://\$(tf output -raw bucket_name)/infra/instance.json - ; echo"
hr "TERRAFORM STATE"
x "tf state list"
x "tf state show aws_instance.web | grep -E '^\s+(id|ami|instance_type|subnet_id|private_ip|public_ip|key_name|user_data)\s'"
x "tf state show aws_route_table.public | sed -n '/route {/,/}/p'"
x "python3 -c \"import json; s=json.load(open('terraform.tfstate')); print('terraform', s['terraform_version'], '| serial', s['serial'], '| resources', len(s['resources'])); [print(' -', r['type']+'.'+r['name'], '-> depends_on', r['instances'][0].get('dependencies', [])) for r in s['resources'] if r['mode']=='managed']\""
hr "TERRAFORM GRAPH (dependencies)"
x "tf graph > ../diagrams/graph.dot && wc -l ../diagrams/graph.dot && grep -c -- '->' ../diagrams/graph.dot"
x "grep -- '->' ../diagrams/graph.dot | sed 's/\"//g; s/^ *//' | sort"
x "dot -Tpng ../diagrams/graph.dot -o ../diagrams/terraform-graph.png && dot -Tsvg ../diagrams/graph.dot -o ../diagrams/terraform-graph.svg && ls -la ../diagrams/"
hr "DRIFT CHECK: plan again"
x "tf plan -input=false $V -detailed-exitcode | tail -3; echo \"exit code: \${PIPESTATUS[0]}  (0 = no changes, 2 = changes pending)\""
hr "SENSITIVE OUTPUT"
x "tf output ssh_private_key_pem"
x "tf output -raw ssh_private_key_pem | head -1; echo '... (only -raw reveals it; it is never stored in git, only in the state file)'"
