apiVersion: v1
kind: Service
metadata:
  name: gitops-webapp-service
  namespace: gitops-prod
  labels:
    app: gitops-webapp
spec:
  type: NodePort
  selector:
    app: gitops-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
