{
 "title": "StudyTrack",
 "tags": [
  "studytrack",
  "24bcs10123"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Backend targets UP",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "sum(up{job=\"studytrack-backend\"})"
    }
   ]
  },
  {
   "title": "Requests / s (all handlers)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"studytrack-backend\"}[1m]))"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"studytrack-backend\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Study minutes logged (total)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(studytrack_minutes_logged_total)"
    }
   ]
  },
  {
   "title": "HTTP requests / s by handler",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total{job=\"studytrack-backend\"}[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP status codes / s",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"studytrack-backend\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Backend pod CPU (cores) vs HPA replicas",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 14, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"studytrack\",container=\"backend\"}[2m]))",
     "legendFormat": "cpu cores (all backend pods)"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"studytrack\",horizontalpodautoscaler=\"studytrack-backend\"}",
     "legendFormat": "hpa replicas"
    }
   ]
  },
  {
   "title": "Backend pod memory",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 14, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"studytrack\",container=\"backend\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}