apiVersion: v1
kind: Namespace
metadata:
  name: p17-devsecops
  labels:
    # reject pods that don't meet the "restricted" Pod Security Standard
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
