#!/usr/bin/env bash
# Session 18 / task 1: the complete Terraform workflow for terraform-s3-demo/ against LocalStack.
cd "$(dirname "$0")/.." && . scripts/lib.sh
cd terraform-s3-demo
V="-var-file=localstack.tfvars"
hr "PROJECT FILES"
x "ls -A"
x "cat terraform.tf provider.tf"
x "cat variables.tf"
x "cat main.tf"
x "cat outputs.tf"
x "cat terraform.tfvars localstack.tfvars"
hr "1. terraform init"
x "rm -rf .terraform terraform.tfstate terraform.tfstate.backup"
x "tf init -input=false"
x "ls -A .terraform/providers/registry.terraform.io/hashicorp/aws/"
hr "2. terraform fmt"
x "tf fmt -recursive -diff; echo \"exit code: \$?\""
hr "3. terraform validate"
x "tf validate"
hr "4. terraform plan"
x "tf plan -input=false $V -out=tfplan"
x "tf show tfplan | grep -E '^  # |Plan:'"
hr "5. terraform apply"
x "tf apply -input=false -auto-approve tfplan"
hr "6. terraform show"
x "tf show"
x "tf state list"
x "tf state show aws_s3_bucket.demo"
hr "7. terraform output"
x "tf output"
x "tf output -raw bucket_arn; echo"
x "tf output -json | python3 -c 'import json,sys; d=json.load(sys.stdin); print({k: v[\"value\"] for k, v in d.items()})'"
hr "8. the bucket really exists - look at it with the AWS CLI"
x "awsl s3 ls"
x "awsl s3api get-bucket-versioning --bucket kushal-24bcs10123-s18-demo"
x "awsl s3api get-bucket-encryption --bucket kushal-24bcs10123-s18-demo"
x "awsl s3api get-public-access-block --bucket kushal-24bcs10123-s18-demo"
x "awsl s3api get-bucket-tagging --bucket kushal-24bcs10123-s18-demo --output table"
x "awsl s3 ls s3://kushal-24bcs10123-s18-demo --recursive"
x "echo 'uploaded outside terraform at '\$(date -u +%FT%TZ) > /tmp/s18-note.txt && awsl s3 cp /tmp/s18-note.txt s3://kushal-24bcs10123-s18-demo/hello/note.txt"
x "awsl s3 cp /tmp/s18-note.txt s3://kushal-24bcs10123-s18-demo/hello/note.txt   # second upload = second version"
x "awsl s3api list-object-versions --bucket kushal-24bcs10123-s18-demo --prefix hello/note.txt --query 'Versions[].{Key:Key,VersionId:VersionId,IsLatest:IsLatest,Size:Size}' --output table"
x "awsl s3 cp s3://kushal-24bcs10123-s18-demo/hello/README.txt -"
hr "9. drift: terraform plan again shows nothing to do (the manual object is not in state, Terraform ignores it)"
x "tf plan -input=false $V -detailed-exitcode | tail -4; echo \"exit code: \${PIPESTATUS[0]}  (0 = no changes, 2 = changes pending)\""
hr "10. change a variable -> plan shows an in-place update"
x "tf plan -input=false $V -var environment=staging | grep -E '~|Plan:'"
hr "11. terraform destroy"
x "tf destroy -input=false -auto-approve $V"
x "awsl s3 ls; echo \"(buckets left: \$(awsl s3 ls | wc -l | tr -d ' '))\""
x "tf state list; echo '(state is empty)'"
x "rm -f tfplan /tmp/s18-note.txt"
