#!/usr/bin/env bash
# Session 18 / task 2: back the aws-services/ notes with real API calls (LocalStack community edition).
cd "$(dirname "$0")/.." && . scripts/lib.sh
hr "01 IAM - users, groups, policies, least privilege"
x "awsl iam create-user --user-name s18-dev-kushal --query 'User.{UserName:UserName,Arn:Arn}'"
x "awsl iam create-group --group-name s18-developers --query 'Group.{GroupName:GroupName,Arn:Arn}'"
x "awsl iam add-user-to-group --user-name s18-dev-kushal --group-name s18-developers"
x "cat aws-services/01-iam/least-privilege-policy.json"
x "awsl iam create-policy --policy-name s18-readonly-one-bucket --policy-document file://aws-services/01-iam/least-privilege-policy.json --query 'Policy.{PolicyName:PolicyName,Arn:Arn}'"
x "awsl iam attach-group-policy --group-name s18-developers --policy-arn arn:aws:iam::000000000000:policy/s18-readonly-one-bucket"
x "awsl iam list-attached-group-policies --group-name s18-developers"
x "awsl iam get-group --group-name s18-developers --query 'Users[].UserName'"
x "cat aws-services/01-iam/ec2-trust-policy.json"
x "awsl iam create-role --role-name s18-ec2-app-role --assume-role-policy-document file://aws-services/01-iam/ec2-trust-policy.json --query 'Role.{RoleName:RoleName,Arn:Arn}'"
x "awsl iam attach-role-policy --role-name s18-ec2-app-role --policy-arn arn:aws:iam::000000000000:policy/s18-readonly-one-bucket"
x "awsl iam create-access-key --user-name s18-dev-kushal --query 'AccessKey.{UserName:UserName,AccessKeyId:AccessKeyId,Status:Status}'"
x "awsl iam list-users --query 'Users[].UserName'"
hr "02 EC2 - AMIs, instance types, key pairs, security groups, EBS, lifecycle"
x "awsl ec2 describe-images --owners amazon --query 'Images[0:3].{ImageId:ImageId,Name:Name,Arch:Architecture}' --output table"
x "awsl ec2 describe-instance-types --instance-types t2.micro t3.micro m5.large --query 'InstanceTypes[].{Type:InstanceType,vCPU:VCpuInfo.DefaultVCpus,MemMiB:MemoryInfo.SizeInMiB}' --output table"
x "awsl ec2 create-key-pair --key-name s18-key --query 'KeyName'"
x "awsl ec2 create-security-group --group-name s18-web-sg --description 'web sg' --query 'GroupId'"
x "awsl ec2 authorize-security-group-ingress --group-name s18-web-sg --protocol tcp --port 22 --cidr 10.0.0.0/8 >/dev/null; awsl ec2 authorize-security-group-ingress --group-name s18-web-sg --protocol tcp --port 80 --cidr 0.0.0.0/0 >/dev/null; awsl ec2 describe-security-groups --group-names s18-web-sg --query 'SecurityGroups[0].IpPermissions[].{Port:FromPort,Cidr:IpRanges[0].CidrIp}' --output table"
x "AMI=\$(awsl ec2 describe-images --owners amazon --query 'Images[0].ImageId' --output text); awsl ec2 run-instances --image-id \$AMI --instance-type t3.micro --key-name s18-key --security-groups s18-web-sg --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=s18-web-1}]' --query 'Instances[0].{InstanceId:InstanceId,State:State.Name,Type:InstanceType,PrivateIp:PrivateIpAddress,PublicIp:PublicIpAddress}'"
x "ID=\$(awsl ec2 describe-instances --filters Name=tag:Name,Values=s18-web-1 --query 'Reservations[0].Instances[0].InstanceId' --output text); echo \$ID > /tmp/s18-instance-id; awsl ec2 describe-instances --instance-ids \$ID --query 'Reservations[0].Instances[0].{State:State.Name,Private:PrivateIpAddress,Public:PublicIpAddress,RootDevice:RootDeviceName}'"
x "awsl ec2 create-volume --size 8 --volume-type gp3 --availability-zone ap-south-1a --query '{VolumeId:VolumeId,Size:Size,Type:VolumeType,State:State}'"
x "VOL=\$(awsl ec2 describe-volumes --query 'Volumes[?Size==\`8\`].VolumeId | [0]' --output text); awsl ec2 attach-volume --volume-id \$VOL --instance-id \$(cat /tmp/s18-instance-id) --device /dev/sdf --query '{Device:Device,State:State}'"
x "awsl ec2 stop-instances --instance-ids \$(cat /tmp/s18-instance-id) --query 'StoppingInstances[0].{Prev:PreviousState.Name,Now:CurrentState.Name}'"
x "awsl ec2 start-instances --instance-ids \$(cat /tmp/s18-instance-id) --query 'StartingInstances[0].{Prev:PreviousState.Name,Now:CurrentState.Name}'"
x "awsl ec2 detach-volume --volume-id \$(awsl ec2 describe-volumes --query 'Volumes[?Size==\`8\`].VolumeId | [0]' --output text) --instance-id \$(cat /tmp/s18-instance-id) --device /dev/sdf --query '{Device:Device,State:State}' || echo '(LocalStack community bug on DetachVolume - on AWS this returns State: detaching)'"
x "awsl ec2 terminate-instances --instance-ids \$(cat /tmp/s18-instance-id) --query 'TerminatingInstances[0].{Prev:PreviousState.Name,Now:CurrentState.Name}' || echo '(LocalStack still thinks the volume is attached - on AWS this returns Now: shutting-down)'"
hr "03 S3 - storage classes, lifecycle rule, bucket policy"
x "awsl s3 mb s3://s18-notes-kushal"
x "echo 'hot data' > /tmp/s18-a.txt; awsl s3 cp /tmp/s18-a.txt s3://s18-notes-kushal/a.txt --storage-class STANDARD; awsl s3 cp /tmp/s18-a.txt s3://s18-notes-kushal/b.txt --storage-class STANDARD_IA; awsl s3 cp /tmp/s18-a.txt s3://s18-notes-kushal/c.txt --storage-class GLACIER"
x "awsl s3api list-objects-v2 --bucket s18-notes-kushal --query 'Contents[].{Key:Key,StorageClass:StorageClass,Size:Size}' --output table"
x "cat aws-services/03-s3/lifecycle.json"
x "awsl s3api put-bucket-lifecycle-configuration --bucket s18-notes-kushal --lifecycle-configuration file://aws-services/03-s3/lifecycle.json && awsl s3api get-bucket-lifecycle-configuration --bucket s18-notes-kushal --query 'Rules[].{ID:ID,Days:Transitions[0].Days,To:Transitions[0].StorageClass,Expire:Expiration.Days}' --output table"
x "cat aws-services/03-s3/bucket-policy.json"
x "awsl s3api put-bucket-policy --bucket s18-notes-kushal --policy file://aws-services/03-s3/bucket-policy.json && awsl s3api get-bucket-policy --bucket s18-notes-kushal --query Policy --output text | python3 -m json.tool | head -12"
x "awsl s3 presign s3://s18-notes-kushal/a.txt --expires-in 60 | sed 's/Signature=.*/Signature=.../'"
hr "04 VPC - the networking pieces (full build is session 19)"
x "awsl ec2 describe-vpcs --query 'Vpcs[].{VpcId:VpcId,Cidr:CidrBlock,Default:IsDefault}' --output table"
x "awsl ec2 describe-subnets --query 'Subnets[].{SubnetId:SubnetId,Cidr:CidrBlock,AZ:AvailabilityZone,PublicIpOnLaunch:MapPublicIpOnLaunch}' --output table"
x "awsl ec2 describe-route-tables --query 'RouteTables[0].Routes[].{Dest:DestinationCidrBlock,Target:GatewayId}' --output table"
x "awsl ec2 describe-network-acls --query 'NetworkAcls[0].Entries[].{Rule:RuleNumber,Egress:Egress,Action:RuleAction,Cidr:CidrBlock}' --output table"
hr "05 DynamoDB - table with partition key + sort key, put / get / query"
x "awsl dynamodb create-table --table-name s18-orders --attribute-definitions AttributeName=customer_id,AttributeType=S AttributeName=order_date,AttributeType=S --key-schema AttributeName=customer_id,KeyType=HASH AttributeName=order_date,KeyType=RANGE --billing-mode PAY_PER_REQUEST --query 'TableDescription.{Table:TableName,Status:TableStatus,Keys:KeySchema}'"
x "awsl dynamodb put-item --table-name s18-orders --item '{\"customer_id\":{\"S\":\"C001\"},\"order_date\":{\"S\":\"2026-10-01\"},\"total\":{\"N\":\"1250\"},\"items\":{\"L\":[{\"S\":\"keyboard\"},{\"S\":\"mouse\"}]}}'"
x "awsl dynamodb put-item --table-name s18-orders --item '{\"customer_id\":{\"S\":\"C001\"},\"order_date\":{\"S\":\"2026-10-05\"},\"total\":{\"N\":\"399\"},\"status\":{\"S\":\"shipped\"}}'"
x "awsl dynamodb put-item --table-name s18-orders --item '{\"customer_id\":{\"S\":\"C002\"},\"order_date\":{\"S\":\"2026-10-03\"},\"total\":{\"N\":\"80\"}}'"
x "awsl dynamodb get-item --table-name s18-orders --key '{\"customer_id\":{\"S\":\"C001\"},\"order_date\":{\"S\":\"2026-10-05\"}}'"
x "awsl dynamodb query --table-name s18-orders --key-condition-expression 'customer_id = :c AND order_date BETWEEN :from AND :to' --expression-attribute-values '{\":c\":{\"S\":\"C001\"},\":from\":{\"S\":\"2026-10-01\"},\":to\":{\"S\":\"2026-10-31\"}}' --query '{Count:Count,Items:Items[].{date:order_date.S,total:total.N}}'"
x "awsl dynamodb scan --table-name s18-orders --select COUNT"
hr "05 RDS - create a Postgres instance (LocalStack community only accepts the API call; the engine itself is a Pro feature)"
x "awsl rds create-db-instance --db-instance-identifier s18-pg --db-instance-class db.t3.micro --engine postgres --master-username admin1 --master-user-password 'NotARealPassw0rd' --allocated-storage 20 --query 'DBInstance.{Id:DBInstanceIdentifier,Engine:Engine,Class:DBInstanceClass,Status:DBInstanceStatus,MultiAZ:MultiAZ}' || echo '(RDS create not available in community edition - see README)'"
x "awsl rds describe-db-instances --query 'DBInstances[].{Id:DBInstanceIdentifier,Engine:Engine,Status:DBInstanceStatus}' 2>&1 | head -12"
hr "CLEANUP"
x "awsl rds delete-db-instance --db-instance-identifier s18-pg --skip-final-snapshot --query 'DBInstance.DBInstanceStatus' 2>/dev/null || true"
x "awsl dynamodb delete-table --table-name s18-orders --query 'TableDescription.TableStatus'"
x "awsl s3 rb s3://s18-notes-kushal --force 2>&1 | tail -1"
x "awsl ec2 delete-security-group --group-name s18-web-sg; awsl ec2 delete-key-pair --key-name s18-key; awsl ec2 delete-volume --volume-id \$(awsl ec2 describe-volumes --query 'Volumes[?Size==\`8\`].VolumeId | [0]' --output text) 2>&1 | tail -1"
x "awsl iam detach-role-policy --role-name s18-ec2-app-role --policy-arn arn:aws:iam::000000000000:policy/s18-readonly-one-bucket; awsl iam delete-role --role-name s18-ec2-app-role"
x "awsl iam detach-group-policy --group-name s18-developers --policy-arn arn:aws:iam::000000000000:policy/s18-readonly-one-bucket; awsl iam delete-policy --policy-arn arn:aws:iam::000000000000:policy/s18-readonly-one-bucket"
x "for k in \$(awsl iam list-access-keys --user-name s18-dev-kushal --query 'AccessKeyMetadata[].AccessKeyId' --output text); do awsl iam delete-access-key --user-name s18-dev-kushal --access-key-id \$k; done; awsl iam remove-user-from-group --user-name s18-dev-kushal --group-name s18-developers; awsl iam delete-group --group-name s18-developers; awsl iam delete-user --user-name s18-dev-kushal; awsl iam list-users --query 'Users[].UserName'"
x "rm -f /tmp/s18-a.txt /tmp/s18-instance-id"
