#!/usr/bin/env bash
# Session 9 / step 2: look at the Kubernetes architecture on the running cluster.
cd "$(dirname "$0")/.." && . scripts/lib.sh
hr "CLUSTER AND NODES"
x "kubectl cluster-info"
x "kubectl get nodes -o wide"
x "kubectl describe node kushal-lab-control-plane | sed -n '/^Labels:/,/^Annotations:/p' | grep -E 'Labels|role|ingress'"
x "kubectl describe node kushal-lab-control-plane | grep -A1 '^Taints:'"
x "kubectl describe node kushal-lab-worker | grep -A6 '^Capacity:'"
hr "CONTROL PLANE COMPONENTS (run as pods in kube-system)"
x "kubectl get pods -n kube-system -o wide"
x "docker exec kushal-lab-control-plane ls /etc/kubernetes/manifests"
x "docker exec kushal-lab-control-plane crictl ps --quiet --name 'kube-apiserver|etcd|kube-scheduler|kube-controller-manager' | wc -l"
x "kubectl get --raw='/livez?verbose' | head -12"
hr "kube-apiserver: the only component everyone talks to"
x "kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'; echo"
x "kubectl api-resources --namespaced=true | head -12"
x "kubectl api-resources | wc -l"
hr "etcd: the cluster database"
ETCD="kubectl -n kube-system exec etcd-kushal-lab-control-plane -- etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key"
x "\$ETCD endpoint status -w table"
x "\$ETCD get /registry/namespaces --prefix --keys-only"
x "\$ETCD get /registry --prefix --keys-only | wc -l      # every object in the cluster is a key here"
hr "kube-scheduler and kube-controller-manager (single active leader each, via Lease objects)"
x "kubectl -n kube-system get leases"
hr "NODE COMPONENTS: kubelet, kube-proxy, container runtime, CNI"
x "docker exec kushal-lab-worker systemctl is-active kubelet containerd"
x "docker exec kushal-lab-worker containerd --version"
x "kubectl get daemonset -n kube-system"
x "kubectl -n kube-system get cm kube-proxy -o jsonpath='{.data.config\.conf}' | grep -E '^mode'"
x "kubectl -n kube-system get svc kube-dns"
x "kubectl -n kube-system get cm coredns -o jsonpath='{.data.Corefile}' | grep -E 'kubernetes|forward'"
