#!/usr/bin/env bash
# Session 9 / step 4: the kubernetes.io "Kubernetes Basics" tutorial flow with kubectl.
cd "$(dirname "$0")/.." && . scripts/lib.sh
hr "Module 2: deploy an app"
x "kubectl create deployment hello-k8s --image=nginx:1.25-alpine --replicas=2"
x "kubectl rollout status deployment/hello-k8s"
x "kubectl get deployments,replicasets,pods -o wide"
hr "Module 3: explore the app"
x "kubectl describe deployment hello-k8s | sed -n '1,12p' | grep -v CreationTimestamp"
POD=$(kubectl get pods -l app=hello-k8s -o jsonpath='{.items[0].metadata.name}')
x "kubectl logs \$POD | tail -3 | sed -E 's#^[0-9/]{10} [0-9:]{8} ##'"
x "kubectl exec \$POD -- nginx -v"
x "kubectl exec \$POD -- cat /etc/hostname"
hr "Module 4: expose the app with a Service"
x "kubectl expose deployment hello-k8s --type=NodePort --port=80"
x "kubectl get svc hello-k8s"
x "kubectl get endpoints hello-k8s"
x "runonce tmp-curl curlimages/curl:8.5.0 -s --retry 5 --retry-connrefused --retry-delay 2 http://hello-k8s | grep -o '<title>.*</title>'   # one-shot pod inside the cluster"
x "kubectl label pods -l app=hello-k8s tier=web"
x "kubectl get pods -l tier=web"
hr "Module 5: scale"
x "kubectl scale deployment/hello-k8s --replicas=4"
x "kubectl rollout status deployment/hello-k8s"
x "kubectl get pods -l app=hello-k8s -o wide"
x "kubectl get endpoints hello-k8s"
x "kubectl scale deployment/hello-k8s --replicas=2"
x "sleep 15; kubectl get deployment hello-k8s; kubectl get pods -l app=hello-k8s"
hr "Module 6: rolling update and rollback"
x "kubectl set image deployment/hello-k8s nginx=nginx:1.27-alpine"
x "kubectl rollout status deployment/hello-k8s"
x "sleep 15; kubectl get pods -l app=hello-k8s -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[0].image,STATUS:.status.phase'"
x "kubectl set image deployment/hello-k8s nginx=nginx:does-not-exist"
x "sleep 15; kubectl get pods -l app=hello-k8s"
x "kubectl rollout status deployment/hello-k8s --timeout=10s || true"
x "kubectl rollout history deployment/hello-k8s"
x "kubectl rollout undo deployment/hello-k8s"
x "kubectl rollout status deployment/hello-k8s"
x "sleep 15; kubectl get pods -l app=hello-k8s -o custom-columns='NAME:.metadata.name,IMAGE:.spec.containers[0].image,STATUS:.status.phase'"
hr "Namespaces"
x "kubectl get namespaces"
x "kubectl create namespace team-a"
x "kubectl -n team-a create deployment web --image=nginx:1.25-alpine"
x "kubectl get pods -n team-a"
x "kubectl get pods            # default namespace does not show team-a pods"
hr "Cleanup"
x "kubectl delete namespace team-a"
x "kubectl delete service,deployment hello-k8s"
