apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: final-devops-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raghav095/devops-heros.git
    targetRevision: HEAD
    path: assignments/session-21/final-devops-project/helm/taskboard
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
