apiVersion: v1
kind: Namespace
metadata:
  name: devsecops
  labels:
    # Reject Pods that don't meet the "restricted" Pod Security Standard
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
