apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - resources.yaml
  - deployment.yaml
commonLabels:
  managed-by: kustomize
  project: devops-final-project
