frontend:
  image: ghcr.io/anshalkumar/labtrack-frontend
  tag: latest
  pullPolicy: IfNotPresent
backend:
  image: ghcr.io/anshalkumar/labtrack-backend
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 2
namespace: labtrack
imagePullSecrets: []
app:
  environment: development
  logLevel: INFO
postgres:
  host: labtrack-postgres
  database: labtrack
  username: labtrack
  password: labtrack
  persistence:
    enabled: true
    size: 5Gi
ingress:
  enabled: false
  host: labtrack.local
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {cpu: 500m, memory: 512Mi}
monitoring:
  serviceMonitor:
    enabled: true
