frontend:
  image: ghcr.io/anshalkumar/labtrack-frontend
backend:
  image: ghcr.io/anshalkumar/labtrack-backend
replicaCount: 2
ingress:
  enabled: true
  host: labtrack.example.com
hpa:
  enabled: true
app:
  environment: production
  logLevel: INFO
