
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: session20-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vvsleepy/devops-heros.git
    targetRevision: main
    path: session20-monitoring-observability-gitops/06-git-as-source-of-truth/gitops-repo/app

  destination:
    server: https://kubernetes.default.svc
    namespace: session20

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
