apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: labtrack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anshalkumar/devops-heros.git
    targetRevision: main
    path: session21-final-devops-project/helm/labtrack
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: ingress.enabled
          value: "false"
        - name: monitoring.serviceMonitor.enabled
          value: "false"
        - name: postgres.persistence.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: labtrack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
