#!/usr/bin/env bash
# lab.md parts 1-9 with the 04-full-demo manifests. Ingress reachable at http://localhost via kind's port mapping;
# `curl --resolve yatri.local:80:127.0.0.1` replaces the /etc/hosts edit from run-demo.sh.
. "$(dirname "$0")/lib.sh"
cd 04-full-demo
R="--resolve yatri.local:80:127.0.0.1"
hr "Part 1: ConfigMap"
x "kubectl apply -f configmap.yaml"
x "kubectl get configmap yatri-app-config"
x "kubectl get configmap yatri-app-config -o jsonpath='{.data.ENVIRONMENT}'; echo"
hr "Part 2: Secret"
x "kubectl apply -f secret.yaml"
x "kubectl get secret yatri-db-secret"
x "kubectl describe secret yatri-db-secret | sed -n '/^Data/,\$p'"
x "kubectl get secret yatri-db-secret -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 --decode; echo"
hr "Part 3: backend reads both as environment variables"
x "kubectl apply -f backend.yaml"
x "kubectl rollout status deployment/yatri-backend --timeout=180s"
x "kubectl get pods -l app=yatri-backend"
x "kubectl exec deployment/yatri-backend -- env | grep -E 'ENVIRONMENT|LOG_LEVEL|APP_PORT|DEFAULT_CURRENCY|MAX_BOOKING_DAYS|POSTGRES' | sort"
hr "Part 4: frontend"
x "kubectl apply -f frontend.yaml"
x "kubectl rollout status deployment/yatri-frontend --timeout=180s"
x "kubectl get svc yatri-frontend-service yatri-backend-service"
hr "Part 5: Ingress"
x "kubectl get pods -n ingress-nginx"
x "kubectl apply -f ingress.yaml"
for i in $(seq 1 30); do [ -n "$(kubectl get ingress yatri-ingress -o jsonpath='{.status.loadBalancer.ingress}')" ] && break; sleep 2; done
x "kubectl get ingress yatri-ingress"
x "kubectl describe ingress yatri-ingress | sed -n '/^Rules/,/^Annotations/p'"
hr "Part 6: test the routing"
x "curl -s $R http://yatri.local/ | grep -i '<title>'"
x "curl -s $R http://yatri.local/api/"
x "curl -s $R -o /dev/null -w 'wrong host header -> HTTP %{http_code}\\n' -H 'Host: nobody.local' http://127.0.0.1/"
x "curl -s -o /dev/null -w 'no host header  -> HTTP %{http_code}\\n' http://localhost/"
hr "Part 7: everything at once"
x "kubectl get configmap yatri-app-config; kubectl get secret yatri-db-secret; kubectl get pods -l app=yatri-frontend; kubectl get pods -l app=yatri-backend; kubectl get svc yatri-frontend-service yatri-backend-service; kubectl get ingress yatri-ingress"
hr "Part 8: the newline bug"
x "echo 'secretpassword' | base64"
x "echo 'c2VjcmV0cGFzc3dvcmQK' | base64 --decode | wc -c"
x "echo -n 'secretpassword' | base64"
x "echo 'c2VjcmV0cGFzc3dvcmQ=' | base64 --decode | wc -c"
hr "Part 9: updating a ConfigMap does not change a running pod's env"
x "kubectl patch configmap yatri-app-config --type merge -p '{\"data\":{\"ENVIRONMENT\":\"staging\"}}'"
x "kubectl get configmap yatri-app-config -o jsonpath='{.data.ENVIRONMENT}'; echo"
x "kubectl exec deployment/yatri-backend -- env | grep ENVIRONMENT"
x "curl -s $R http://yatri.local/api/ | grep ENVIRONMENT"
x "kubectl rollout restart deployment/yatri-backend && kubectl rollout status deployment/yatri-backend"
x "kubectl exec deployment/yatri-backend -- env | grep ENVIRONMENT"
sleep 5   # give the ingress controller a moment to pick up the new pod IPs
x "for i in 1 2 3 4; do curl -s $R http://yatri.local/api/ | grep ENVIRONMENT; done | sort | uniq -c"
x "kubectl patch configmap yatri-app-config --type merge -p '{\"data\":{\"ENVIRONMENT\":\"production\"}}' && kubectl rollout restart deployment/yatri-backend && kubectl rollout status deployment/yatri-backend"
