#!/usr/bin/env bash
# 03-ingress hands-on: host-based routing + TLS termination, reusing the running yatri frontend/backend.
. "$(dirname "$0")/lib.sh"
T="kushal-24bcs10123/tls-tmp"; mkdir -p "$T"
x "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $T/tls.key -out $T/tls.crt -subj '/CN=campus.local/O=CampusDevOps' 2>&1 | tail -1"
x "kubectl create secret tls campus-tls-cert --cert=$T/tls.crt --key=$T/tls.key"
x "kubectl get secret campus-tls-cert"
x "kubectl apply -f 03-ingress/ingress-tls.yaml"
for i in $(seq 1 30); do [ -n "$(kubectl get ingress campus-ingress-tls -o jsonpath='{.status.loadBalancer.ingress}')" ] && break; sleep 2; done; sleep 5
x "kubectl get ingress"
x "kubectl describe ingress campus-ingress-tls | sed -n '/^TLS/,/^Annotations/p'"
hr "host-based routing over HTTPS (self-signed, so -k)"
x "curl -sk --resolve portal.campus.local:443:127.0.0.1 https://portal.campus.local/ | grep -i '<title>'"
x "curl -sk --resolve api.campus.local:443:127.0.0.1 https://api.campus.local/api/ | head -3"
x "curl -sk --resolve api.campus.local:443:127.0.0.1 -o /dev/null -w 'api host, frontend path -> HTTP %{http_code}\\n' https://api.campus.local/"
x "curl -s --resolve portal.campus.local:80:127.0.0.1 -o /dev/null -w 'plain http -> HTTP %{http_code} redirect to %{redirect_url}\\n' http://portal.campus.local/"
x "echo | openssl s_client -connect 127.0.0.1:443 -servername portal.campus.local 2>/dev/null | openssl x509 -noout -subject -issuer"
x "echo | openssl s_client -connect 127.0.0.1:443 -servername yatri.local 2>/dev/null | openssl x509 -noout -subject    # host without TLS config gets the controller's default cert"
hr "Why the lab's cert was not used: CN=campus.local, no SAN -> does not match portal./api.campus.local"
x "kubectl -n ingress-nginx logs deploy/ingress-nginx-controller | grep 'does not contain a Common Name' | tail -1 | sed -E 's/^W[0-9]+ [0-9:.]+ +[0-9]+ [a-z_]+\\.go:[0-9]+\\] //'"
x "openssl x509 -in $T/tls.crt -noout -subject -ext subjectAltName 2>&1 | head -3"
hr "Fix: issue the cert with Subject Alternative Names for both hosts and replace the secret"
x "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $T/tls.key -out $T/tls.crt -subj '/CN=campus.local/O=CampusDevOps' -addext 'subjectAltName=DNS:portal.campus.local,DNS:api.campus.local' 2>&1 | tail -1"
x "kubectl delete secret campus-tls-cert && kubectl create secret tls campus-tls-cert --cert=$T/tls.crt --key=$T/tls.key"
sleep 8
x "echo | openssl s_client -connect 127.0.0.1:443 -servername portal.campus.local 2>/dev/null | openssl x509 -noout -subject -ext subjectAltName"
x "curl -s --cacert $T/tls.crt --resolve portal.campus.local:443:127.0.0.1 -o /dev/null -w 'https://portal.campus.local with the cert trusted, no -k -> HTTP %{http_code}\\n' https://portal.campus.local/"
x "curl -s --cacert $T/tls.crt --resolve api.campus.local:443:127.0.0.1 https://api.campus.local/api/ | head -2"
hr "Cleanup (TLS lab + full demo)"
x "kubectl delete ingress campus-ingress-tls && kubectl delete secret campus-tls-cert"
rm -rf "$T"
x "bash 04-full-demo/cleanup.sh"
x "kubectl get all -l app=yatri-app; kubectl get configmap yatri-app-config; kubectl get secret yatri-db-secret; kubectl get ingress yatri-ingress"
