apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bare-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bare-rs
  template:
    metadata:
      labels:
        app: bare-rs
    spec:
      containers:
        - name: web
          image: nginx:1.25
