#!/usr/bin/env bash
# LoadBalancer: needs something outside Kubernetes to hand out the IP. In the cloud that is the cloud
# controller (AWS ELB etc); on kind/bare metal I use MetalLB, configured from kushal-24bcs10123/metallb-pool.yaml.
. "$(dirname "$0")/lib.sh"
x "kubectl apply -f 03-loadbalancer/app-deployment.yaml"
x "kubectl apply -f 03-loadbalancer/service.yaml"
x "kubectl rollout status deployment/web-app-loadbalancer"
x "kubectl get pods -l app=web-loadbalancer"
hr "Without a load-balancer provider the EXTERNAL-IP stays <pending> forever"
x "sleep 5; kubectl get svc web-service-loadbalancer"
x "kubectl get svc web-service-loadbalancer -o jsonpath='a LoadBalancer is also a NodePort underneath: nodePort={.spec.ports[0].nodePort}{\"\\n\"}'"
x "curl -s -m 3 -o /dev/null -w 'via the auto-allocated NodePort on a node: HTTP %{http_code}\\n' http://localhost:\$(kubectl get svc web-service-loadbalancer -o jsonpath='{.spec.ports[0].nodePort}') || echo '(that NodePort is not one of the ports kind maps to the Mac, expected)'"
hr "Install MetalLB and give it a pool of IPs from the docker 'kind' network"
x "docker network inspect kind -f '{{range .IPAM.Config}}{{.Subnet}} {{end}}'"
x "kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.15.3/config/manifests/metallb-native.yaml | tail -3"
x "kubectl wait -n metallb-system --for=condition=ready pod --selector=app=metallb --timeout=240s"
x "kubectl get pods -n metallb-system -o wide"
x "cat kushal-24bcs10123/metallb-pool.yaml"
x "kubectl apply -f kushal-24bcs10123/metallb-pool.yaml"
for i in $(seq 1 30); do [ -n "$(kubectl get svc web-service-loadbalancer -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" ] && break; sleep 2; done
hr "Now the same Service gets an EXTERNAL-IP"
x "kubectl get svc web-service-loadbalancer"
LBIP=$(kubectl get svc web-service-loadbalancer -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
x "kubectl describe svc web-service-loadbalancer | grep -E '^(Type|IP|LoadBalancer Ingress|Port|NodePort|Endpoints)'"
x "kubectl get events --field-selector involvedObject.name=web-service-loadbalancer -o custom-columns='REASON:.reason,MESSAGE:.message'"
hr "Reach the app on the load balancer IP from outside the cluster (another container on the docker network = 'the office LAN')"
x "docker run --rm --network kind curlimages/curl:8.5.0 -s -m 5 http://$LBIP | grep -o '<title>.*</title>'"
x "for i in 1 2 3; do docker run --rm --network kind curlimages/curl:8.5.0 -s -m 5 -o /dev/null -w 'http://$LBIP -> HTTP %{http_code}\\n' http://$LBIP; done"
x "docker run --rm --network kind alpine:3.20 sh -c 'apk add -q iproute2 >/dev/null 2>&1; ping -c1 -W1 $LBIP >/dev/null; ip neigh show $LBIP'   # which node's MAC answers ARP for the LB IP"
x "kubectl get nodes -o wide | awk '{print \$1, \$6}'"
hr "Cleanup"
x "kubectl delete -f 03-loadbalancer/service.yaml -f 03-loadbalancer/app-deployment.yaml"
x "kubectl delete -f kushal-24bcs10123/metallb-pool.yaml"
x "kubectl delete -f https://raw.githubusercontent.com/metallb/metallb/v0.15.3/config/manifests/metallb-native.yaml --ignore-not-found | tail -2"
