#!/usr/bin/env bash
# ExternalName: a CNAME inside cluster DNS pointing at something outside the cluster.
. "$(dirname "$0")/lib.sh"
x "kubectl apply -f 04-externalname/service.yaml"
x "kubectl get svc external-database-service"
x "kubectl apply -f 04-externalname/client-pod.yaml"
x "kubectl wait --for=condition=Ready pod/dns-test-client --timeout=120s"
hr "CoreDNS answers with a CNAME - no ClusterIP, no endpoints, no kube-proxy rules"
x "kubectl exec dns-test-client -- nslookup external-database-service 2>/dev/null | grep 'canonical name' | head -1"
x "kubectl get endpointslices -l kubernetes.io/service-name=external-database-service"
x "docker exec kushal-lab-worker iptables -t nat -S | grep -c external-database-service"
hr "The alias is only as good as its target: nencyravaliya.me has no DNS record at the moment"
x "kubectl exec dns-test-client -- nslookup nencyravaliya.me 2>&1 | grep -m1 -iE 'NXDOMAIN|Address: [0-9]'"
x "dig +short nencyravaliya.me A | head -1; echo '(empty = no A record, checked from the Mac too)'"
x "kubectl exec dns-test-client -- curl -s -m 5 -o /dev/null -w 'HTTP %{http_code}\\n' http://external-database-service || echo 'curl exit 6 = could not resolve host (the CNAME target does not exist)'"
hr "Same thing pointed at a real host, so the traffic path can be seen end to end"
x "kubectl create service externalname external-api --external-name=api.github.com"
x "kubectl exec dns-test-client -- nslookup external-api 2>/dev/null | grep -E 'canonical name|^Address: [0-9]' | head -2"
x "kubectl exec dns-test-client -- curl -s -m 10 -o /dev/null -w 'http://external-api  (Host: api.github.com) -> HTTP %{http_code}, connected to %{remote_ip}\\n' -H 'Host: api.github.com' http://external-api"
x "kubectl exec dns-test-client -- curl -s -m 10 -o /dev/null -w 'https://external-api -> HTTP %{http_code}\\n' https://external-api 2>&1 || echo '(exit 60: the TLS certificate is for api.github.com, not for the alias name - the client must use the real hostname for HTTPS)'"
x "kubectl exec dns-test-client -- curl -s -m 10 -o /dev/null -w 'https://api.github.com directly -> HTTP %{http_code}\\n' https://api.github.com"
hr "Cleanup"
x "kubectl delete svc external-api"
x "kubectl delete -f 04-externalname/client-pod.yaml -f 04-externalname/service.yaml"
