#!/usr/bin/env bash
# Headless service (clusterIP: None): DNS returns the pod IPs themselves; StatefulSet pods get their own names.
. "$(dirname "$0")/lib.sh"
x "kubectl apply -f 05-headless/service.yaml"
x "kubectl apply -f 05-headless/app-statefulset.yaml"
x "kubectl apply -f 05-headless/client-pod.yaml"
x "kubectl rollout status statefulset/web-stateful"
x "kubectl wait --for=condition=Ready pod/headless-dns-client --timeout=120s"
x "kubectl get svc web-service-headless          # CLUSTER-IP is None"
x "kubectl get pods -l app=web-headless -o wide"
hr "Service name -> ALL pod IPs (no VIP in between)"
x "kubectl exec headless-dns-client -- nslookup web-service-headless 2>/dev/null | grep -E '^Address: 10\\.' | sort -u"
hr "Each pod has its own stable DNS name"
x "kubectl exec headless-dns-client -- nslookup web-stateful-0.web-service-headless.default.svc.cluster.local 2>/dev/null | grep -E '^(Name|Address: 10)'"
x "kubectl exec headless-dns-client -- nslookup web-stateful-2.web-service-headless.default.svc.cluster.local 2>/dev/null | grep -E '^(Name|Address: 10)'"
for i in 0 1 2; do kubectl exec web-stateful-$i -- sh -c "echo hello from web-stateful-$i > /usr/share/nginx/html/index.html"; done
x "kubectl exec headless-dns-client -- curl -s http://web-stateful-0.web-service-headless:80"
x "kubectl exec headless-dns-client -- curl -s http://web-stateful-1.web-service-headless:80"
x "kubectl exec headless-dns-client -- curl -s http://web-stateful-2.web-service-headless:80"
x "for i in 1 2 3 4 5 6; do kubectl exec headless-dns-client -- curl -s http://web-service-headless:80; done | sort | uniq -c   # client-side choice, not kube-proxy"
hr "A pod comes back with the same name and DNS entry"
x "kubectl delete pod web-stateful-1 && kubectl rollout status statefulset/web-stateful"
x "kubectl get pod web-stateful-1 -o wide"
x "kubectl exec headless-dns-client -- nslookup web-stateful-1.web-service-headless.default.svc.cluster.local 2>/dev/null | grep -E '^(Name|Address: 10)'   # same name, new IP"
hr "Compare with a normal ClusterIP service on the same pods"
x "kubectl create service clusterip web-service-normal --tcp=80 && kubectl set selector svc web-service-normal app=web-headless"
x "sleep 2; kubectl exec headless-dns-client -- nslookup web-service-normal 2>/dev/null | grep -E '^Address: 10'        # one virtual IP for the same 3 pods"
x "kubectl get svc web-service-headless web-service-normal"
hr "Cleanup"
x "kubectl delete svc web-service-normal"
x "kubectl delete -f 05-headless/client-pod.yaml -f 05-headless/app-statefulset.yaml -f 05-headless/service.yaml"
