{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "taskboard.fullname" . }}-backend
  labels:
    release: {{ .Values.monitoring.release | default "monitoring" | quote }}
spec:
  selector:
    matchLabels: {app: taskboard-backend}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
